{
 "title": "Metrics demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counter",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rate(demo_counter[5m])", "legendFormat": "clicks" }
     ]
    },
    {
     "title": "Counter current value",
     "type": "stat",
     "description": "Value after last service restart",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "demo_counter" }
     ]
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gauge (delta for 5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "delta(demo_gauge[5m])" }
     ]
    },
    {
     "title": "Gauge current value",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "demo_gauge" }
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Histogram",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "demo_histogram_bucket", "legendFormat": "{{le}}" }
     ]
    },
    {
     "title": "Requests count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "demo_histogram_count" }
     ]
    },
    {
     "title": "Histogram quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, demo_histogram_bucket)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, demo_histogram_bucket)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "demo_histogram_sum / demo_histogram_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal API requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Histogram (/api/counter)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "api_requests_duration_seconds_bucket{handler=\"/api/counter\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Histogram (/api/gauge)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "api_requests_duration_seconds_bucket{handler=\"/api/gauge\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Histogram (/api/histogram)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "api_requests_duration_seconds_bucket{handler=\"/api/histogram\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Requests count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(api_requests_duration_seconds_count)"
      }
     ]
    },
    {
     "title": "Histogram quantile",
     "type": "graph",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, api_requests_duration_seconds_bucket{handler=\"/api/counter\"})",
       "legendFormat": "p95 counter"
      },
      {
       "expr": "histogram_quantile(0.95, api_requests_duration_seconds_bucket{handler=\"/api/gauge\"})",
       "legendFormat": "p95 gauge"
      },
      {
       "expr": "histogram_quantile(0.95, api_requests_duration_seconds_bucket{handler=\"/api/histogram\"})",
       "legendFormat": "p95 histogram"
      }
     ]
    }
   ]
  },
  { "title": "External API requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests count (code=200)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_requests_duration_seconds_count{code=\"200\"}"
    }
   ]
  },
  {
   "title": "Errors count (code!=200)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_requests_duration_seconds_count{code!=\"200\"}"
    }
   ]
  },
  {
   "title": "Rate of errors count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(github_requests_duration_seconds_count{code!=\"200\"}[5m])"
    }
   ]
  },
  {
   "title": "Histogram quantile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, github_requests_duration_seconds_bucket{code=\"200\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, github_requests_duration_seconds_bucket{code=\"200\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, github_requests_duration_seconds_bucket{code=\"200\"})",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}